name: Run All Tests

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  tests:
    runs-on: windows-latest
    
    steps:
      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1.1.0
      
      - run: (Get-Command 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe').Version.ToString()
